const express= require('express')
const { placeOrder, verifyOrder, userOrder, Allorder, updateStatus } = require('../controller/orderController')
const authMiddleware = require('../utils/authMiddle')
const orderRoutes=express.Router()
orderRoutes.post('/place',authMiddleware, placeOrder)
orderRoutes.post('/verify',verifyOrder)
orderRoutes.get('/user-order',authMiddleware, userOrder)
orderRoutes.get('/all-order', Allorder)
orderRoutes.put('/status', updateStatus)
module.exports=orderRoutes